list: $/mberizzo/faq/models/faqcategory/columns.yaml
modelClass: Mberizzo\Faq\Models\FaqCategory
title: Categories
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mberizzo/faq/categories/update/:id'
